### ISSUE TITLE
Eduardo - Issues

### ISSUE THREAD

**Issue by LucasAlves71** [Edumorais08/projeto-react#3]
### Descrição

São funcionalidades/requisitos que foram separados para cada integrante do grupo.

### Critérios de Aceitação

- [x] O sistema deverá possuir uma página inicial listando duas (à livre escolha) categorias de filmes disponibilizadas pela API, sendo elas: Now playing, Popular,  Top rated, Upcoming;
- [x] A listagem deverá exibir o pôster, nome e data de lançamento dos filmes;
- [x] Ao clicar em um filme da lista, o sistema deverá redirecionar o usuário para uma página com mais detalhes;
- [x] A página de detalhes deverá conter: Nome, data de lançamento, pôster, nota e gênero;
- [x] A página de detalhes deverá conter uma sessão exibindo pelo menos 5 pessoas do elenco do filme em questão com nome original, nome do personagem e foto.

**Comment by Edumorais08** [comment]
terminei
